---
title: "World Happiness 2020"
author: "Aarushi Gupta"
date: "11/9/2020"
output: html_document
---

```{r message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(DT)
library(tidyverse)
library(ggplot2)
library(forcats)
```

## Part 1

First, we load the data into R.

```{r warning = FALSE, message = FALSE}
# First, we load the data into R. 
data2020 <- read.csv("~/Desktop/Clubs/DataRes/2020.csv")
data2019 <- read.csv("~/Desktop/Clubs/DataRes/2019.csv")
data2018 <- read.csv("~/Desktop/Clubs/DataRes/2018.csv")
data2017 <- read.csv("~/Desktop/Clubs/DataRes/2017.csv")
data2016 <- read.csv("~/Desktop/Clubs/DataRes/2016.csv")
data2015 <- read.csv("~/Desktop/Clubs/DataRes/2015.csv")

# Then, we summarize and rename columns in the 2020 data. 
head(data2020)
score_2020 <- data2020[c(2,3, 7:12)]  %>% group_by(`Regional.indicator`) %>% 
  summarize (`Ladder score` = mean(`Ladder.score`), `Logged GDP per capita` = mean(`Logged.GDP.per.capita`), `Social support` = mean(`Social.support`), `Healthy life expectancy` = mean(`Healthy.life.expectancy`), `Freedom to make life choices` = mean(`Freedom.to.make.life.choices`), `Generosity` = mean(`Generosity`), `Perceptions of corruption` = mean(`Perceptions.of.corruption`))
colnames(score_2020) = c("Region", "Score", "GDP", "Social Support", "Life Expectancy", "Freedom", "Generosity", "Corruption")
head(score_2020)
```

## Part 2

```{r warning = FALSE, message = FALSE}
# First, select and rename all the relevant variables for each year. 
data_2020 <- data2020[c(1,3,7,9:12)] %>% rename("country" = "Country.name", "score_20" = "Ladder.score", "gdp_20" = "Logged.GDP.per.capita", "health_20" = "Healthy.life.expectancy", "freedom_20" = "Freedom.to.make.life.choices", "generosity_20" = "Generosity", "trust_20" = "Perceptions.of.corruption")
data_2020[78,1] = "Hong Kong"
data_2019 <- data2019[c(2:4,6:9)] %>% rename("country" = "Country.or.region", "score_19" = "Score", "gdp_19" = "GDP.per.capita", "health_19" = "Healthy.life.expectancy", "freedom_19" = "Freedom.to.make.life.choices", "generosity_19" = "Generosity", "trust_19" = "Perceptions.of.corruption")
data_2018 <- data2018[c(2:4,6:9)] %>% rename("country" = "Country.or.region", "score_18" = "Score", "gdp_18" = "GDP.per.capita", "health_18" = "Healthy.life.expectancy", "freedom_18" = "Freedom.to.make.life.choices", "generosity_18" = "Generosity", "trust_18" = "Perceptions.of.corruption")
data_2017 <- data2017[c(1,3,6,8:11)] %>% rename("country" = "Country", "score_17" = "Happiness.Score", "gdp_17" = "Economy..GDP.per.Capita.", "health_17" = "Health..Life.Expectancy.", "freedom_17" = "Freedom", "generosity_17" = "Generosity", "trust_17" = "Trust..Government.Corruption.")
data_2017[71,1] = "Hong Kong"
data_2016 <- data2016[c(1,4,7,9,10,12,11)] %>% rename("country" = "Country", "score_16" = "Happiness.Score", "gdp_16" = "Economy..GDP.per.Capita.", "health_16" = "Health..Life.Expectancy.", "freedom_16" = "Freedom", "generosity_16" = "Generosity", "trust_16" = "Trust..Government.Corruption.")
data_2015 <- data2015[c(1,4,6,8,9,11,10)] %>% rename("country" = "Country", "score_15" = "Happiness.Score", "gdp_15" = "Economy..GDP.per.Capita.", "health_15" = "Health..Life.Expectancy.", "freedom_15" = "Freedom", "generosity_15" = "Generosity", "trust_15" = "Trust..Government.Corruption.")

# Then, combine the datasets by country name using the inner_join() function.
fulldata <- data_2020 %>% 
  inner_join(data_2019, by = "country") %>% 
  inner_join(data_2018, by = "country") %>% 
  inner_join(data_2017, by = "country") %>% 
  inner_join(data_2016, by = "country") %>% 
  inner_join(data_2015, by = "country")
```

## Part 3

```{r warning = FALSE, message = FALSE}
# Classify each country's location into one of 10 different regions. 
fulldata$col38 = fulldata$country
fulldata <- fulldata %>% rename("region" = "col38")
fulldata <- fulldata[c(1,38,2,8,14,20,26,32,3,9,15,21,27,33,4,10,16,22,28,34,5,11,17,23,29,35,6,12,18,24,30,36,7,13,19,25,31,37)]
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Western Europe" = "Finland", "Western Europe" = "Denmark", "Western Europe" = "Switzerland", "Western Europe" = "Iceland", "Western Europe" = "Norway", "Western Europe" = "Netherlands", "Western Europe" = "Sweden", "Western Europe" = "Austria", "Western Europe" = "Luxembourg", "Western Europe" = "Norway", "Western Europe" = "Ireland", "Western Europe" = "Belgium", "Western Europe" = "United Kingdom", "Western Europe" = "Germany", "Western Europe" = "France", "Western Europe" = "Spain", "Western Europe" = "Malta", "Western Europe" = "Italy", "Western Europe" = "North Cyprus", "Western Europe" = "Cyprus", "Western Europe" = "Portugal", "Western Europe" = "Greece"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "North America" = "United States", "North America" = "Canada"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Australia & New Zealand" = "Australia", "Australia & New Zealand" = "New Zealand"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Middle East & North Africa" = "Israel", "Middle East & North Africa" = "United Arab Emirates", "Middle East & North Africa" = "Saudi Arabia", "Middle East & North Africa" = "Bahrain", "Middle East & North Africa" = "Kuwait", "Middle East & North Africa" = "Libya", "Middle East & North Africa" = "Turkey", "Middle East & North Africa" = "Jordan", "Middle East & North Africa" = "Morocco", "Middle East & North Africa" = "Algeria", "Middle East & North Africa" = "Iraq", "Middle East & North Africa" = "Lebanon", "Middle East & North Africa" = "Iran", "Middle East & North Africa" = "Palestinian Territories", "Middle East & North Africa" = "Tunisia", "Middle East & North Africa" = "Egypt", "Middle East & North Africa" = "Yemen"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Central & Eastern Europe" = "Czech Republic", "Central & Eastern Europe" = "Slovenia", "Central & Eastern Europe" = "Kosovo", "Central & Eastern Europe" = "Slovakia", "Central & Eastern Europe" = "Lithuania", "Central & Eastern Europe" = "Poland", "Central & Eastern Europe" = "Romania", "Central & Eastern Europe" = "Estonia", "Central & Eastern Europe" = "Hungary", "Central & Eastern Europe" = "Latvia", "Central & Eastern Europe" = "Serbia", "Central & Eastern Europe" = "Bosnia and Herzegovina", "Central & Eastern Europe" = "Montenegro", "Central & Eastern Europe" = "Croatia", "Central & Eastern Europe" = "Macedonia", "Central & Eastern Europe" = "Bulgaria", "Central & Eastern Europe" = "Albania", "Central & Eastern Europe" = "Uzbekistan", "Central & Eastern Europe" = "Kazakhstan", "Central & Eastern Europe" = "Moldova", "Central & Eastern Europe" = "Tajikistan", "Central & Eastern Europe" = "Russia", "Central & Eastern Europe" = "Kyrgyzstan", "Central & Eastern Europe" = "Belarus", "Central & Eastern Europe" = "Azerbaijan", "Central & Eastern Europe" = "Turkmenistan", "Central & Eastern Europe" = "Armenia", "Central & Eastern Europe" = "Georgia", "Central & Eastern Europe" = "Ukraine"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Latin America & Caribbean" = "Costa Rica", "Latin America & Caribbean" = "Mexico", "Latin America & Caribbean" = "Uruguay", "Latin America & Caribbean" = "Guatemala", "Latin America & Caribbean" = "Brazil", "Latin America & Caribbean" = "El Salvador", "Latin America & Caribbean" = "Panama", "Latin America & Caribbean" = "Chile", "Latin America & Caribbean" = "Trinidad and Tobago", "Latin America & Caribbean" = "Colombia", "Latin America & Caribbean" = "Nicaragua", "Latin America & Caribbean" = "Argentina", "Latin America & Caribbean" = "Honduras", "Latin America & Caribbean" = "Ecuador", "Latin America & Caribbean" = "Jamaica", "Latin America & Caribbean" = "Peru", "Latin America & Caribbean" = "Bolivia", "Latin America & Caribbean" = "Paraguay", "Latin America & Caribbean" = "Dominican Republic", "Latin America & Caribbean" = "Venezuela", "Latin America & Caribbean" = "Haiti"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "East Asia" = "Taiwan", "East Asia" = "South Korea", "East Asia" = "Japan", "East Asia" = "Hong Kong", "East Asia" = "Mongolia", "East Asia" = "China"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Southeast Asia" = "Singapore", "Southeast Asia" = "Thailand", "Southeast Asia" = "Philippines", "Southeast Asia" = "Malaysia", "Southeast Asia" = "Vietnam", "Southeast Asia" = "Indonesia", "Southeast Asia" = "Laos", "Southeast Asia" = "Cambodia", "Southeast Asia" = "Myanmar"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "South Asia" = "Pakistan", "South Asia" = "Bangladesh", "South Asia" = "Nepal", "South Asia" = "Sri Lanka", "South Asia" = "India", "South Asia" = "Afghanistan"))
fulldata <- fulldata %>% mutate(`region` = fct_recode(`region`, "Sub-Saharan Africa" = "Mauritius", "Sub-Saharan Africa" = "Ivory Coast", "Sub-Saharan Africa" = "Benin", "Sub-Saharan Africa" = "Congo (Brazzaville)", "Sub-Saharan Africa" = "Congo (Kinshasa)", "Sub-Saharan Africa" = "Ghana", "Sub-Saharan Africa" = "Cameroon", "Sub-Saharan Africa" = "Senegal", "Sub-Saharan Africa" = "Guinea", "Sub-Saharan Africa" = "Niger", "Sub-Saharan Africa" = "Gabon", "Sub-Saharan Africa" = "South Africa", "Sub-Saharan Africa" = "Burkina Faso", "Sub-Saharan Africa" = "Gambia", "Sub-Saharan Africa" = "Mali", "Sub-Saharan Africa" = "Nigeria", "Sub-Saharan Africa" = "Mozambique", "Sub-Saharan Africa" = "Kenya", "Sub-Saharan Africa" = "Namibia", "Sub-Saharan Africa" = "Liberia", "Sub-Saharan Africa" = "Uganda", "Sub-Saharan Africa" = "Chad", "Sub-Saharan Africa" = "Mauritania", "Sub-Saharan Africa" = "Swaziland", "Sub-Saharan Africa" = "Comoros", "Sub-Saharan Africa" = "Togo", "Sub-Saharan Africa" = "Ehiopia", "Sub-Saharan Africa" = "Madagascar", "Sub-Saharan Africa" = "Sierra Leone", "Sub-Saharan Africa" = "Burundi", "Sub-Saharan Africa" = "Zambia", "Sub-Saharan Africa" = "Lesotho", "Sub-Saharan Africa" = "Malawi", "Sub-Saharan Africa" = "Botswana", "Sub-Saharan Africa" = "Tanzia", "Sub-Saharan Africa" = "Central African Republic", "Sub-Saharan Africa" = "Rwanda", "Sub-Saharan Africa" = "Zimbabwe", "Sub-Saharan Africa" = "South Sudan", "Sub-Saharan Africa" = "Ethiopia", "Sub-Saharan Africa" = "Tanzania"))
```

## Part 4

```{r warning = FALSE, message = FALSE, fig.height = 7, fig.width = 11}
# Take out the UAE because it is N/A and ensure all numeric data is num
fulldata <- fulldata %>% slice(-21)
fulldata$trust_18 <- as.numeric(fulldata$trust_18)
str(fulldata)

# Then, calculate the mean of every variable by region. 
fullregion <- fulldata[2:8] %>% group_by(region) %>% summarize_all("mean")
skip2020 <- fulldata[c(2,4:8,10:14,16:20,22:26,28:32,34:38)] %>% group_by(region) %>% summarize_all("mean")
fullskip2020 <- fulldata[c(1,4:8,10:14,16:20,22:26,28:32,34:38)] 
full2020 <- fulldata[c(1,3,9,15,21,27,33)]

# Save the cleaned data into a spreadsheet to create visualizations. 
write.csv(fullregion,"~/Desktop/Clubs/DataRes/20201221.csv", row.names = FALSE)
write.csv(skip2020,"~/Desktop/Clubs/DataRes/2015to2019.csv", row.names = FALSE)
write.csv(fullskip2020,"~/Desktop/Clubs/DataRes/country15to19.csv", row.names = FALSE)
write.csv(full2020,"~/Desktop/Clubs/DataRes/country2020.csv", row.names = FALSE)
```
